security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    app_user_provider:
      entity:
        class: App\Entity\Personne
        property: email
    oauth_user_provider:
      id: App\Security\GoogleOAuthUserProvider
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      entry_point: App\Security\AdaptiveMFAAuthenticator
      custom_authenticators:
        - App\Security\AdaptiveMFAAuthenticator
      oauth:
        resource_owners:
          google: /connect/check-google
        login_path: app_login
        use_forward: false
        failure_path: app_login
        oauth_user_provider:
          service: App\Security\GoogleOAuthUserProvider
      logout:
        path: app_logout
        # where to redirect after logout
        target: app_login

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
<<<<<<< HEAD
    - { path: ^/admin/reservations/\d+/status$, roles: ROLE_ADMIN, methods: [POST] }
=======
    - { path: ^/connect, roles: PUBLIC_ACCESS }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
>>>>>>> a7ca2b7f98856d56cec0c9b7e46065622ed36879
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/postes, roles: [PUBLIC_ACCESS] } # Allow viewing posts, but maybe restrict creation/edit later

when@test:
  security:
    password_hashers:
      # By default, password hashers are resource intensive and take time. This is
      # important to generate secure password hashes. In tests however, secure hashes
      # are not important, waste resources and increase test times. The following
      # reduces the work factor to the lowest possible values.
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
